<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Enums\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Rules\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Rules\**" />
    <None Remove="Enums\**" />
    <None Remove="Models\**" />
    <None Remove="Rules\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
